
server.port: 8333
spring.h2.console.enabled: true



# Datasource
#datasource.checkin.url: jdbc:h2:mem:dev;DB_CLOSE_DELAY=20;DB_CLOSE_ON_EXIT=false;MODE=MySQL
#datasource.checkin.schema: classpath:schema.sql
#datasource.checkin.data: classpath:data.sql
##datasource.checkin.username: checkin
#datasource.checkin.password: checkin
#datasource.checkin.driver-class-name: org.h2.Driver
#datasource.checkin.testOnBorrow: true
#datasource.checkin.validationQuery: SELECT 1 FROM DUAL
#datasource.checkin.validationInterval: 30000
#datasource.checkin.autoCommit: true
