INSERT INTO USER_DETAILS (EMP_ID, NAME, EMAIL, MOBILE_NUMBER, ROLE, TEAM, PROFILE_PIC)
VALUES ('1','Venkatraman', 'venkatraman.vr@tre.se','07622334202','Developer','Finance General', NULL );

INSERT INTO USER_DETAILS (EMP_ID, NAME, EMAIL, MOBILE_NUMBER, ROLE, TEAM, PROFILE_PIC)
VALUES ('2','Alaa', 'alaa@tre.se','07624421212','Developer','Finance General', NULL );

INSERT INTO LOCATION_INFO (LOCATION_ID, FLOOR_PLAN)
VALUES ('F01A01D001', NULL);

INSERT INTO LOCATION_INFO (LOCATION_ID, FLOOR_PLAN)
VALUES ('F01A01D011', NULL);

INSERT INTO LOCATION_INFO (LOCATION_ID, FLOOR_PLAN)
VALUES ('F02A01D022', NULL);

INSERT INTO LOCATION_INFO (LOCATION_ID, FLOOR_PLAN)
VALUES ('F04A01D044', NULL);

INSERT INTO LOCATION_INFO (LOCATION_ID, FLOOR_PLAN)
VALUES ('F03A01D033', NULL);
